### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by RobLoach** [IgniparousTempest/libretro-superflappybirds#5]
Love what you did with this :smile: 

Does it work with netplay???

Interesting engine too. Been looking for better graphic backends than SDL for [ChaiLove](https://github.com/libretro/libretro-chailove). Experimented with [libretro-cairo](https://github.com/RobLoach/libretro-cairo) too, to see if [Cairo](https://www.cairographics.org/) would be a good option. What are your future plans for [engine](https://github.com/IgniparousTempest/libretro-superflappybirds/tree/master/engine)?

**Comment by Renetrox** [comment]
Please tell me how I can add it to lakka!!

**Comment by RobLoach** [comment]
Build it, and then upload the built .so file to your Lakka box's /cores directory in Samba :wink: 

Going to close this one for now. In the mean time, I've made a [TIC-80](https://tic.computer/) core you might also have interest in!
